export const urunAgentConfig = {
  openrouter: {
    textModel: "meta-llama/llama-3.3-70b-instruct",
    textModels: [
      { value: "meta-llama/llama-3.3-70b-instruct", label: "Llama 3.3 70B", description: "Meta, dengeli ve kaliteli", cost: "ücretli" },
      { value: "openai/gpt-4o-mini", label: "GPT-4o Mini", description: "OpenAI, hızlı ve ucuz", cost: "$0.15/1M token" },
      { value: "openai/gpt-4o", label: "GPT-4o", description: "OpenAI, çok yönlü", cost: "$2.50/1M token" },
      { value: "google/gemini-2.5-flash", label: "Gemini 2.5 Flash", description: "Google, hızlı", cost: "$0.15/1M token" },
      { value: "anthropic/claude-sonnet-4.5", label: "Claude Sonnet 4.5", description: "Anthropic, yaratıcı metinler", cost: "$3.00/1M token" },
      { value: "deepseek/deepseek-chat", label: "DeepSeek V3", description: "DeepSeek, uygun fiyatlı", cost: "$0.27/1M token" },
      { value: "mistralai/mistral-small-24b-instruct-2501", label: "Mistral Small 3", description: "Mistral, hızlı ve kaliteli", cost: "$0.10/1M token" },
      { value: "qwen/qwen-2.5-72b-instruct", label: "Qwen2.5 72B", description: "Qwen, güçlü", cost: "$0.35/1M token" },
    ],
    imageModels: [
      {
        value: "black-forest-labs/flux-1.1-pro",
        label: "Flux Pro 1.1",
        description: "Harika fotogerçekçilik, ürün fotoğrafçılığı için ideal",
        cost: "$0.04/görsel",
        realistic: 9,
      },
      {
        value: "google/gemini-3.1-flash-image",
        label: "Nano Banana 2 (Gemini 3.1 Flash)",
        description: "En iyi fiyat/kalite oranı, çok gerçekçi",
        cost: "$0.039/görsel",
        realistic: 10,
      },
      {
        value: "black-forest-labs/flux.2-pro",
        label: "Flux 2 Pro",
        description: "En yeni Flux, malzeme ve doku kalitesi en üst seviye",
        cost: "$0.03/MP",
        realistic: 10,
      },
      {
        value: "google/gemini-3-pro-image",
        label: "Nano Banana Pro (Gemini 3 Pro)",
        description: "En gerçekçi model, profesyonel çekim kalitesi",
        cost: "$0.10/görsel",
        realistic: 10,
      },
      {
        value: "bytedance-seed/seedream-4.5",
        label: "Seedream 4.5",
        description: "ByteDance'in son modeli, iyi detay",
        cost: "$0.04/görsel",
        realistic: 8,
      },
    ],
    defaultImageModel: "black-forest-labs/flux-1.1-pro",
    temperature: 0.7,
    maxTokens: 2048,
  },
  defaults: {
    photoCount: 2,
    resolution: "1K",
    aspectRatio: "1:1",
    quality: "high",
    styles: [
      { value: "minimal", label: "Minimal / Sade" },
      { value: "luks", label: "Lüks / Premium" },
      { value: "dogal", label: "Doğal / Günlük" },
      { value: "canli", label: "Canlı / Renkli" },
      { value: "editorial", label: "Editoryal / Moda Çekimi" },
    ],
    stylePrompts: {
      minimal: "clean white background, soft studio lighting, minimal accessories, professional product photography, ultra realistic, 8K",
      luks: "dramatic lighting, premium luxurious setting, elegant composition, gold accents, ultra realistic, high-end fashion photography, 8K",
      dogal: "outdoor natural lighting, casual lifestyle setting, authentic, soft bokeh background, ultra realistic, natural skin tones, 8K",
      canli: "vibrant colors, bold background, energetic composition, bright natural lighting, ultra realistic, fashion editorial style, 8K",
      editorial: "high fashion magazine style, artistic composition, dramatic contrast, studio lighting, ultra realistic, editorial photography, 8K",
    },
    textTypes: [
      { value: "description", label: "Ürün Açıklaması" },
      { value: "instagram", label: "Instagram Post" },
      { value: "facebook", label: "Facebook Reklam" },
      { value: "email", label: "E-posta Kampanyası" },
    ],
    tones: [
      { value: "samimi", label: "Samimi" },
      { value: "luks", label: "Lüks" },
      { value: "genc", label: "Genç / Enerjik" },
      { value: "profesyonel", label: "Profesyonel" },
    ],
    videoTypes: [
      { value: "tanitim", label: "Ürün Tanıtımı" },
      { value: "kampanya", label: "Sezon Kampanyası" },
      { value: "sosyal-medya", label: "Sosyal Medya (Shorts/Reels)" },
    ],
  },
}
